# Generated by Django 3.1.4 on 2020-12-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warden',
            name='phoneno',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
