# Generated by Django 3.1.3 on 2021-01-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0005_auto_20210105_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_mbl_no',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_mbl_no',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
