# Generated by Django 3.1.3 on 2021-01-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0006_auto_20210105_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='vacant',
            field=models.CharField(max_length=10),
        ),
    ]
