# Generated by Django 3.1.3 on 2021-01-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0007_auto_20210108_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='vacant',
            field=models.BooleanField(default=False),
        ),
    ]
