# Generated by Django 3.1.3 on 2021-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0008_auto_20210108_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warden',
            name='phoneno',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
