# Generated by Django 3.1.3 on 2021-01-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0009_auto_20210108_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='created_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapp.student')),
            ],
        ),
    ]
